### ISSUE TITLE
Buy anti-cheat?

### ISSUE THREAD

**Issue by exrex90** [bartico6/Phantasm#1]
Hello. Where can I buy anti-cheat?

**Comment by bartico6** [comment]
The anticheat isn't available for purchase because it is not finished/production ready yet, nor is it a project that I am willing to sell to anyone. If you are interested in purchasing the anticheat once it is ready, please continue following this repository. I plan to provide the anticheat as a service/subscription rather than a single purchase/software copy+license.

Thank you for your interest, however!

**Comment by exrex90** [comment]
when is the release?

**Comment by bartico6** [comment]
Once the anticheat is completed and ready for use. I still have some things to figure out before its ready, seen in the repository readme.
